from app.models.area import Area
from app.models.choice import Choice
from app.models.course import Course
from app.models.assessment import Assessment
from app.models.period import Period
from app.models.question import Question
from app.models.subtopic import Subtopic
from app.models.topic import Topic
from app.models.assessment_type import AssessmentType
from app.models.question_type import QuestionType
from app.models.modality import Mapped