from app.models.area import Area
from app.models.choice import Choice
from app.models.course import Course
from app.models.difficulty import Difficulty
from app.models.exam import Exam
from app.models.period import Period
from app.models.question import Question
from app.models.subtopic import Subtopic
from app.models.topic import Topic
from app.models.type_exam import TypeExam
from app.models.type_question import TypeQuestion