"""add column subtopic to question

Revision ID: 3c8a2f2fd3fc
Revises: 4d6c04488788
Create Date: 2026-02-01 21:37:35.505385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8a2f2fd3fc'
down_revision: Union[str, Sequence[str], None] = '4d6c04488788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subtopic_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questions_subtopic_id'), 'questions', ['subtopic_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'subtopics', ['subtopic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_subtopic_id'), table_name='questions')
    op.drop_column('questions', 'subtopic_id')
    # ### end Alembic commands ###
